# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('0', 'Smart Phone'), ('1', 'Home Phone'), ('2', 'Cell Phone')], max_length=2)),
                ('value', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('foundation_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('0', 'White'), ('1', 'Black'), ('2', 'Grey'), ('3', 'Blue')], max_length=2)),
                ('screen_size', models.CharField(max_length=20)),
                ('screen_type', models.CharField(choices=[('0', 'Super Amoled'), ('1', 'IPS LCD'), ('2', 'Amoled')], max_length=2)),
                ('camera', models.CharField(max_length=5)),
                ('battery_capacity', models.CharField(max_length=5)),
                ('memory', models.CharField(max_length=5)),
                ('storage', models.CharField(max_length=5)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PhoneBrand')),
            ],
        ),
    ]
